stdcxx: prevent refs to weak symbols w/o definition
When executing

  make KERNEL=hw BOARD=virt_qemu_riscv TEST_PKGS=test-stdcxx TEST_SRCS=run/depot_autopilot

we experienced errors like

  Error: LD: symbol not found: 'transaction clone for operator new[](unsigned long)'

This issue seems to be caused by weak undefined symbols of libitm and
seems to be related to

  https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=69506

Thus, we define _GLIBCXX_USE_WEAK_REF 0 like its done in newlib and
darwin environments and, thereby, drop ITM support.

Fixes #5607